imports:
    - { resource: util.yml }
    - { resource: form.yml }
    - { resource: twig.yml }

services:
    radnok_payu.payment_factory:
        class: RadnoK\PayUBundle\Payment\PaymentFactory
        arguments:
            - "%payu_environment%"
            - "%payu_client_id%"
            - "%payu_client_secret%"

    radnok_payu.new_payment.listener:
        class: RadnoK\PayUBundle\EventListener\NewPaymentListener
        arguments:
            - "@radnok_payu.util.subscription_manipulator"
            - "@radnok_payu.util.order_manipulator"
            - "@radnok_payu.payment_factory"
            - "@event_dispatcher"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    radnok_payu.payment_status.listener:
        class: RadnoK\PayUBundle\EventListener\PaymentStatusListener
        arguments:
            - "@radnok_payu.util.subscription_manipulator"
        tags:
            - { name: kernel.event_subscriber }

    radnok_payu.order_manager:
        class: RadnoK\PayUBundle\Doctrine\OrderManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%radnok_payu_model_order_class%"

    radnok_payu.subscription_manager:
        class: RadnoK\PayUBundle\Doctrine\SubscriptionManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%radnok_payu_model_subscription_class%"

