services:
    radnok_payu.recurring_payment:
        class: RadnoK\PayUBundle\Payment\RecurringPayment
        arguments:
            - "@router"

    radnok_payu.single_payment:
        class: RadnoK\PayUBundle\Payment\SinglePayment
        arguments:
            - "@router"

    radnok_payu.payment_manager:
        class: RadnoK\PayUBundle\Manager\PaymentManager
        arguments:
            - "@radnok_payu.single_payment"
            - "@radnok_payu.recurring_payment"

    radnok_payu.listener:
        class: RadnoK\PayUBundle\EventListener\PaymentListener
        arguments:
            - "@radnok_payu.payment_manager"
            - "@doctrine.orm.entity_manager"
            - "%payu_environment%"
            - "%payu_client_id%"
            - "%payu_client_secret%"
        tags:
            - { name: kernel.event_subscriber }

    radnok_payu.plan.form.type:
        class: RadnoK\PayUBundle\Form\PlanType
        tags:
            - { name: form.type }
        arguments: ["%radnok_model_plan_class%"]